baseURL: "https://aniskhan001.me/"
title: "Anis Khan"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pluralizeListTitles: false

googleAnalytics: G-HKTS2WR0QV
disqusShortname: aniskhan001

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Anis Khan
    description: "Enjoying life"
    keywords: [Blog, Tech, Life, PaperMod]
    author: Anis Khan
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/icon/favicon.ico"
        favicon16x16: "/icon/favicon16x16.png"
        favicon32x32: "/icon/favicon32x32.png"
        apple_touch_icon: "/icon/apple_touch_icon.png"
        safari_pinned_tab: "/icon/apple_touch_icon.png"

    label:
        text: "Home"
        icon: /icon/favicon.ico
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Anis Khan
        subtitle: I write in a text editor
        imageUrl: img/profile.jpg
        imageWidth: 120
        imageHeight: 120
        imageTitle: Anis Khan
        # buttons:
        #     - name: Life Blogs
        #       url: life
        #     - name: Tech Blogs
        #       url: tech

    socialIcons:
        - name: twitter
          url: "https://twitter.com/aniskhan001"
        - name: github
          url: "https://github.com/aniskhan001"
        - name: linkedin
          url: "https://linkedin.com/in/aniskhan001"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/1712600/aniskhan001"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/aniskhan001.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    # main:
    #     - identifier: tech
    #       name: tech
    #       url: /tech/
    #       weight: 5
    #     - identifier: life
    #       name: life
    #       url: /life/
    #       weight: 5
    #     - identifier: categories
    #       name: categories
    #       pre: <i data-feather="circle"></i>
    #       url: /categories/
    #       weight: 10
    #     - identifier: tags
    #       name: tags
    #       url: /tags/
    #       weight: 20
    #     - identifier: search
    #       name: search
    #       pre: <i class='fa fa-road'></i>
    #       url: /search/
    #       weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
